package com.backend.service;

import com.backend.model.BookingRequest;
import com.backend.model.ServiceCenter;
import com.backend.model.VehicleModel;
import com.backend.model.VehicleType;
import com.backend.repository.BookingRequestRepository;
import com.backend.repository.ServiceCenterRepository;
import com.backend.repository.VehicleModelRepository;
import com.backend.repository.VehicleTypeRepository;
import com.backend.service.EmailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class BookingRequestService {

    @Autowired
    private BookingRequestRepository repository;

    @Autowired
    private VehicleTypeRepository vehicleTypeRepository;

    @Autowired
    private VehicleModelRepository vehicleModelRepository;

    @Autowired
    private ServiceCenterRepository serviceCenterRepository;

    @Autowired
    private EmailService emailService;

    public BookingRequest createBooking(BookingRequest booking) {
        // Set timestamps
        LocalDateTime now = LocalDateTime.now();
        booking.setCreatedAt(now);
        booking.setUpdatedAt(now);
        // Ensure ID is not set by client (auto-generated by DB)
        booking.setId(null);
        BookingRequest savedBooking = repository.save(booking);

        // Fetch IDs and names for vehicle type, vehicle model, and service center
        String vehicleTypeId = String.valueOf(savedBooking.getVehicleTypeId());
        String vehicleTypeName = "Unknown";
        String vehicleModelId = String.valueOf(savedBooking.getVehicleModelId());
        String vehicleModelName = "Unknown";
        String serviceCenterId = String.valueOf(savedBooking.getServiceCenterId());
        String serviceCenterName = "Unknown";

        try {
            Optional<VehicleType> vehicleType = vehicleTypeRepository.findById(savedBooking.getVehicleTypeId());
            if (vehicleType.isPresent()) {
                vehicleTypeName = vehicleType.get().getName();
            }

            Optional<VehicleModel> vehicleModel = vehicleModelRepository.findById(savedBooking.getVehicleModelId());
            if (vehicleModel.isPresent()) {
                vehicleModelName = vehicleModel.get().getModelName();
            }

            Optional<ServiceCenter> serviceCenter = serviceCenterRepository.findById(savedBooking.getServiceCenterId());
            if (serviceCenter.isPresent()) {
                serviceCenterName = serviceCenter.get().getCenterName() + " (" + serviceCenter.get().getCityName() + ")";
            }
        } catch (Exception e) {
            System.err.println("Error fetching details for email: " + e.getMessage());
        }

        // Send confirmation email to the customer with both IDs and names
        try {
            emailService.sendBookingConfirmationEmail(
                savedBooking.getCustomerEmail(),
                savedBooking.getCustomerName(),
                savedBooking,
                vehicleTypeId,
                vehicleTypeName,
                vehicleModelId,
                vehicleModelName,
                serviceCenterId,
                serviceCenterName
            );
        } catch (Exception e) {
            System.err.println("Failed to send booking confirmation email: " + e.getMessage());
        }

        return savedBooking;
    }

    public List<BookingRequest> getBookingsByCustomerId(Long customerId) {
        return repository.findByCustomerId(customerId);
    }

    public Optional<BookingRequest> getBookingById(Long id) {
        return repository.findById(id);
    }

    public BookingRequest updateBooking(Long id, BookingRequest booking) {
        BookingRequest existing = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Booking not found with id: " + id));
        existing.setCustomerName(booking.getCustomerName());
        existing.setCustomerPhone(booking.getCustomerPhone());
        existing.setCustomerEmail(booking.getCustomerEmail());
        existing.setAddress(booking.getAddress());
        existing.setServices(booking.getServices());
        existing.setPickDropOption(booking.getPickDropOption());
        existing.setPickupAddress(booking.getPickupAddress());
        existing.setDropAddress(booking.getDropAddress());
        existing.setPickupDropoffOption(booking.getPickupDropoffOption());
        existing.setRequestedDate(booking.getRequestedDate());
        existing.setStatus(booking.getStatus());
        existing.setVehicleRegistrationNumber(booking.getVehicleRegistrationNumber());
        existing.setUpdatedAt(LocalDateTime.now());
        return repository.save(existing);
    }

    public void deleteBooking(Long id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Booking not found with id: " + id);
        }
        repository.deleteById(id);
    }
}